### ISSUE TITLE
Suporte a mais idiomas?

### ISSUE THREAD

**Issue by rafaeleyng** [CWISoftware/blog#1]
Posso fazer com suporte a tradução de posts. A pessoa poderia fazer um post em português e/ou inglês e linkar um ao outro.

A pergunta é: queremos isso?

Eu acho que não precisa, pela ideia do blog.

**Comment by brunotrassante** [comment]
Acho que na primeira versão não precisamos. Quando o blog estiver famoso na comunidade e com muitos acessos internacionais gente adiciona a feature. =P

**Comment by rafaeleyng** [comment]
Concordo e fechou.
