### ISSUE TITLE
Funcionamento

### ISSUE THREAD

**Issue by robsonbittencourt** [CWISoftware/blog#2]
Como vai funcionar este blog? Teria alguma coisa que eu possa ajudar?

**Comment by brunotrassante** [comment]
O blog será uma subistituição do blog atual do drops que temos. Com uma cara mais clean e a facilidade de postar similar ao do Eventos. Quem está puxando o projeto eh o @rafaeleyng. Troca uma ideia com ele, mas em breve teremos um readMe com mais detalhes =D

**Comment by robsonbittencourt** [comment]
Blz, vou falar com ele. Valeu!
